export class CommodityConstants {
  /**
   * Index of home tab.
   */
  static readonly INDEX_HOME: number = 0;

  /**
   * Index of shopCart tab.
   */
  static readonly INDEX_SHOPPING_CART: number = 2;

  /**
   * The stars of rating.
   */
  static readonly RATING_STARS: number = 5

  /**
   * Text max line value: 2
   */
  static readonly MAX_LINE: number = 2;

  /**
   * String of choose.
   */
  static readonly SPECIAL_CHOOSE: string = '已选';

  /**
   * ConfirmOrderPage url.
   */
  static readonly CONFIRM_ORDER_PAGE_URL: string = 'pages/ConfirmOrderPage';
}