export class PageConstants {
  /**
   * Delay time to router MainPage.
   */
  static readonly DELAY_TIME: number = 5000;

  /**
   * The value of letter space: 16vp.
   */
  static readonly LETTER_SPACE: string = '16vp';

  /**
   * The value of tab bar button space: 6vp.
   */
  static readonly BUTTON_SPACE: string = '6vp';

  /**
   * MainPage url.
   */
  static readonly  MAIN_PAGE_URL: string = 'pages/MainPage';

  /**
   * Image aspect ratio value: 1.
   */
  static readonly IMAGE_ASPECT_RATIO: number = 1;

  /**
   * Key of router get params: id.
   */
  static readonly ID_KEY: string = 'id';
}