/**
 * Constants for Grid components.
 */
export class GridConstants {
  /**
   * Current component width: 4 grids.
   */
  static readonly COLUMN_FOUR: number = 4;

  /**
   * Current component width: 8 grids.
   */
  static readonly COLUMN_EIGHT: number = 8;

  /**
   * Current component width: 12 grids.
   */
  static readonly COLUMN_TWELVE: number = 12;

  /**
   * Current component width: 1 grids.
   */
  static readonly SPAN_ONE: number = 1;

  /**
   * Current component width: 2 grids.
   */
  static readonly SPAN_TWO: number = 2;

  /**
   * Current component width: 3 grids.
   */
  static readonly SPAN_THREE: number = 3;

  /**
   * Current component width: 4 grids.
   */
  static readonly SPAN_FOUR: number = 4;

  /**
   * Current component width: 8 grids.
   */
  static readonly SPAN_EIGHT: number = 8;

  /**
   * Current component width: 12 grids.
   */
  static readonly SPAN_TWELVE: number = 12;

  /**
   * Current component offset 2 grids.
   */
  static readonly OFFSET_TWO: number = 2;

  /**
   * Current component offset 3 grids.
   */
  static readonly OFFSET_THREE: number = 3;

  /**
   * Current component offset 6 grids.
   */
  static readonly OFFSET_SIX: number = 6;

  /**
   * Current component offset 8 grids.
   */
  static readonly OFFSET_EIGHT: number = 8;

  /**
   * Current component gutter 12.
   */
  static readonly GUTTER_TWELVE: number = 12;
}