export class PersonalConstants {
  /**
   * Index of pending payment tab.
   */
  static readonly PENDING_PAYMENT_INDEX: number = 1;

  /**
   * Index of waiting shipping tab.
   */
  static readonly WAITING_SHIPMENT_INDEX: number = 2;

  /**
   * Index of waiting received tab.
   */
  static readonly WAITING_RECEIVED_INDEX: number = 3;

  /**
   * Index of waiting evaluate tab.
   */
  static readonly WAITING_EVALUATE_INDEX: number = 4;

  /**
   * Size of badge.
   */
  static readonly BADGE_SIZE: number = 16;

  /**
   * Live list item image aspect ration of sm.
   */
  static readonly ASPECT_RATIO_SM: number = 1.09;

  /**
   * Live list item image aspect ration of md.
   */
  static readonly ASPECT_RATIO_MD: number = 1.51;

  /**
   * Live list item image aspect ration of lg.
   */
  static readonly ASPECT_RATIO_LG: number = 1.63;

  /**
   * OrderDetailListPage url.
   */
  static readonly ORDER_LIST_PAGE_URL: string = 'pages/OrderDetailListPage';
}